services:
  onfly-api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    env_file:
    - .env
    ports:
      - 3000:3000
    command: npm run start:dev
    environment:
      - DB_TYPE=DB_TYPE
      - DB_HOST=DB_HOST
      - DB_PORT=DB_PORT
      - DB_USERNAME=DB_USERNAME
      - DB_PASSWORD=DB_PASSWORD
      - DB_NAME=DB_NAME


  postgres:
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432" # hostport to containerport
