services:
  onfly-api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    env_file:
    - .env
    ports:
      - 3000:3000
    command: npm run start:dev
    networks:
      - app


  postgres:
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432" # hostport to containerport
    networks:
      - app

  redis:
    image: redis:latest
    env_file:
      - .env
    environment:
      - name=value
    ports:
      - "6379:6379"
    networks:
      - app


networks:
  app:
    driver: bridge
